"""add page_count to notices

Revision ID: 37a10f17493f
Revises: c28c766a5e3d
Create Date: 2026-04-09 09:02:35.884679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a10f17493f'
down_revision: Union[str, Sequence[str], None] = 'c28c766a5e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('page_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'page_count')
    # ### end Alembic commands ###
