"""make publish_end nullable

Revision ID: daa01a1e7b35
Revises: 37a10f17493f
Create Date: 2026-04-09 14:46:46.536971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa01a1e7b35'
down_revision: Union[str, Sequence[str], None] = '37a10f17493f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('publish_end',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('publish_end',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
